import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  sectionTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: 12,
    marginBottom: 8,
    marginTop: 8,
  },
  audiobookGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    marginHorizontal: 8,
    marginBottom: 20,
  },
  audiobookCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    marginRight: "2%",
    alignItems: "flex-start",
    position: "relative",
    minHeight: 80,
  },
  premiumText: {
    color: "#29e33e",
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 2,
  },
  audiobookTitle: {
    color: "#111",
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 2,
  },
  audiobookAuthor: {
    color: "#666",
    fontSize: 13,
  },
  radioCircle: {
    position: "absolute",
    right: 12,
    bottom: 18,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#111",
    backgroundColor: "#fff",
  },
  heartCircle: {
    position: "absolute",
    right: 12,
    bottom: 12,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  heartIcon: {
    width: 18,
    height: 18,
  },
  audiobookImage: {
    width: 54,
    height: 54,
    alignSelf: "center",
    marginBottom: 8,
    marginTop: 8,
  },
  heartCircleIcon: {
    position: "absolute",
    right: 12,
    top: 12,
    width: 28,
    height: 28,
  },
  audiobookCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    marginRight: "2%",
    alignItems: "flex-start",
    position: "relative",
    minHeight: 140,
  },
  premiumText: {
    color: "#29e33e",
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 2,
  },
  audiobookTitle: {
    color: "#111",
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 2,
  },
  audiobookAuthor: {
    color: "#666",
    fontSize: 13,
  },
});

export default styles;
